name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Operator SDK
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: github
        operator-sdk: '1.35.0'

    - name: Check OperatorSDK version
      run: operator-sdk version

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'

    - name: Check Go version
      run: go version
    
    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: make test
